name: Backend CICD
on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  packages: write

jobs:
  backend-deploy:
    name: Backend Deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [service-registry, api-gateway, ramp]
    defaults:
      run:
        working-directory: backend/${{ matrix.directory }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build project with Maven
        run: mvn clean package -DskipTests

      - name: Login to GHCR
        run: |
          echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build the backend image and push it to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ramp-backend-${{ matrix.directory }}:v${{ github.run_number }}
          context: backend/${{ matrix.directory }}
